### ISSUE TITLE
Cannot access service by IP (localhost or 127.0.0.1 works)

### ISSUE THREAD

**Issue by surecc** [tomashanacek/mock-server#20]
I can't access the service from my own IP, but 127.0.0.1 works
can you tell me why and help me out?

when i start with : 

mock-server --address=119.254.100.35 --dir=/root/mockServer

it occours:

Traceback (most recent call last):
  File "/usr/local/bin/mock-server", line 66, in <module>
    main()
  File "/usr/local/bin/mock-server", line 60, in main
    server.bind(options.port, options.address)
  File "/usr/local/lib/python2.7/site-packages/tornado/tcpserver.py", line 170, in bind
    backlog=backlog)
  File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/local/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by sanmaopep** [comment]
I can't access too

**Comment by sanmaopep** [comment]
You can use nginx make a proxy.

**Comment by sagespidy** [comment]
> You can use nginx to make a proxy.

Thanks

**Comment by kdyzm** [comment]
> You can use nginx to make a proxy.

This is a good idea, but this bug needs to be fixed.

**Comment by golharam** [comment]
Its not a bug, the server is only listening on the loop-back address, 127.0.0.1.  Looks like there is a '--address' which you can use to specify the IP address to listen to.

**Comment by DmitryAndreyeff** [comment]
Try adding --address=0.0.0.0
