### ISSUE TITLE
HTTPHeaders object is not JSON serializable (tornado 4.3)

### ISSUE THREAD

**Issue by jorisroovers** [tomashanacek/mock-server#22]
I just ran into an issue where mock-server raises an exception if http headers are passed. See the exception below where I've set an HTTP header called ```myheader````.

```bash
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/foo/bar', version='HTTP/1.1', remote_ip='::1', headers={'Content-Length': '296', 'Accept-Encoding': 'gzip, deflate', 'Http_myheader': 'foo123', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'python-requests/2.8.1', 'Connection': 'keep-alive', 'Content-Type': 'application/json'})
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1603, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mock_server/handlers.py", line 123, in post
    self._resolve_request(path, format)
  File "/usr/lib/python2.7/site-packages/mock_server/handlers.py", line 213, in _resolve_request
    self.log_request(response)
  File "/usr/lib/python2.7/site-packages/mock_server/handlers.py", line 74, in log_request
    model.add_to_resources_log(self.log_request_name, data)
  File "/usr/lib/python2.7/site-packages/mock_server/model.py", line 379, in add_to_resources_log
    f.write("%s\n" % json.dumps(data, cls=ExtendedJSONEncoder))
  File "/usr/lib64/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/site-packages/mock_server/util.py", line 38, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <tornado.httputil.HTTPHeaders object at 0x2482bd0> is not JSON serializable
```
I was able to pinpoint that this issue to tornado 4.3. This issue does not occur in tornado versions 4.2 or below. I think the fix is as straightforward as fixing ```tornado<4.3, >=3.1``` in requirements.txt

**Comment by hoda0013** [comment]
I seem to be getting this same error. This is the first time I've used this so I've never had it working.

I attempted to clone the project and do as the user above suggest by changing the requirements.txt and re-running however i still get the same error.

**Comment by jorisroovers** [comment]
@hoda0013 I suggest doing ```pip install mock-server tornado==4.2``` as a workaround. My suggestion was for a more permanent fix.

**Comment by hoda0013** [comment]
Nice. That worked perfectly. Thank you!

**Comment by jingjingpiggy** [comment]
@jorisroovers nice! thank you!

**Comment by sunriseXu** [comment]
@jorisroovers nice! thank you!

**Comment by tomashanacek** [comment]
Hi, I just released a new version. Should be fixed in version 0.3.9
