### ISSUE TITLE
No longer installs [for python3.9]

### ISSUE THREAD

**Issue by withtwoemms** [tomashanacek/mock-server#39]
when trying to install with python v3.9.14, a transitive dependency conflict arrises between [`py-bcrypt`](https://pypi.org/project/py-bcrypt/#history) and [`futures`](https://pypi.org/project/futures/#history) over the versions of the [`metadata`](https://pypi.org/project/metadata/#history) package.

```
Collecting tornado==4.3
  Downloading tornado-4.3.tar.gz (450 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 450.9/450.9 KB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting markdown2>=2.1.0
  Downloading markdown2-2.4.6-py2.py3-none-any.whl (37 kB)
Collecting py-bcrypt>=0.3
  Downloading py-bcrypt-0.4.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
Collecting futures>=2.1.3
  Downloading futures-3.0.5.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/Users/withtwoemms/.pyenv/versions/mock-server/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
          from setuptools.dist import Distribution
        File "/Users/withtwoemms/.pyenv/versions/mock-server/lib/python3.9/site-packages/setuptools/dist.py", line 32, in <module>
          from setuptools.extern.more_itertools import unique_everseen
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 565, in module_from_spec
        File "/Users/withtwoemms/.pyenv/versions/mock-server/lib/python3.9/site-packages/setuptools/extern/__init__.py", line 52, in create_module
          return self.load_module(spec.name)
        File "/Users/withtwoemms/.pyenv/versions/mock-server/lib/python3.9/site-packages/setuptools/extern/__init__.py", line 37, in load_module
          __import__(extant)
        File "/Users/withtwoemms/.pyenv/versions/mock-server/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/__init__.py", line 1, in <module>
          from .more import *  # noqa
        File "/Users/withtwoemms/.pyenv/versions/mock-server/lib/python3.9/site-packages/setuptools/_vendor/more_itertools/more.py", line 5, in <module>
          from concurrent.futures import ThreadPoolExecutor
        File "/private/var/folders/85/t66vqlvs15n3vk9441vsw74w0000gr/T/pip-install-in_dzwj0/futures_2107073ab68246ba84c2c2e934dfd990/concurrent/futures/__init__.py", line 8, in <module>
          from concurrent.futures._base import (FIRST_COMPLETED,
        File "/private/var/folders/85/t66vqlvs15n3vk9441vsw74w0000gr/T/pip-install-in_dzwj0/futures_2107073ab68246ba84c2c2e934dfd990/concurrent/futures/_base.py", line 357
          raise type(self._exception), self._exception, self._traceback
                                     ^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by withtwoemms** [comment]
dispute resolved in #40 by capping the `futures` dependency at v2.2.0.

**Comment by withtwoemms** [comment]
will assay other python versions to better understand the contagion of this issue.

**Comment by withtwoemms** [comment]
✅ 3.7.x
✅ 3.8.x
❌ 3.9.x
✅ 3.10.x

tried a few patch versions in python versions 3.7 - 3.10 and it seems this is an issue installing with python 3.9.x. doesn't seem to be widespread, but still might be good to cap that dependency.
